# Generated by Django 4.1.2 on 2022-10-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=200)),
                ('app_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('WARNING', 'WARNING'), ('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=50)),
                ('message', models.TextField()),
                ('logged_on', models.DateTimeField(auto_now_add=True)),
                ('warning_cnt_two_hrs', models.IntegerField()),
                ('agg_error_cnt_two_hrs', models.IntegerField()),
            ],
        ),
    ]
