# Generated by Django 4.1.2 on 2022-10-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logged_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
